-- Expense categories now use HMRC's official Making Tax Digital names (periodExpenses fields).
UPDATE "Expense" SET "hmrcCategory" = CASE "category"
    WHEN 'FUEL' THEN 'carVanTravelExpenses'
    WHEN 'VEHICLE_MAINTENANCE' THEN 'carVanTravelExpenses'
    WHEN 'VEHICLE_COSTS' THEN 'carVanTravelExpenses'
    WHEN 'SUPPLIES' THEN 'costOfGoods'
    WHEN 'SUBCONTRACTORS' THEN 'paymentsToSubcontractors'
    WHEN 'WAGES' THEN 'wagesAndStaffCosts'
    WHEN 'PREMISES' THEN 'premisesRunningCosts'
    WHEN 'INSURANCE' THEN 'premisesRunningCosts'
    WHEN 'EQUIPMENT_REPAIRS' THEN 'maintenanceCosts'
    WHEN 'OFFICE' THEN 'adminCosts'
    WHEN 'SOFTWARE' THEN 'adminCosts'
    WHEN 'MARKETING' THEN 'advertisingCosts'
    WHEN 'ENTERTAINMENT' THEN 'businessEntertainmentCosts'
    WHEN 'LOAN_INTEREST' THEN 'interestOnBankOtherLoans'
    WHEN 'BANK_FEES' THEN 'financeCharges'
    WHEN 'BAD_DEBTS' THEN 'irrecoverableDebts'
    WHEN 'PROFESSIONAL_FEES' THEN 'professionalFees'
    WHEN 'EQUIPMENT' THEN 'otherExpenses'
    WHEN 'CLOTHING' THEN 'otherExpenses'
    WHEN 'TRAINING' THEN 'otherExpenses'
    WHEN 'OTHER' THEN 'otherExpenses'
    WHEN 'OPENING' THEN 'otherExpenses'
    ELSE 'otherExpenses'
  END;
