import { chromium } from "playwright";
const B="http://localhost:3000";
const browser = await chromium.launch({ executablePath: "/tmp/chromium", args: ["--no-sandbox","--disable-gpu","--single-process","--no-zygote","--disable-dev-shm-usage"] });
const page = await (await browser.newContext({ timezoneId: "UTC", locale: "en-GB", viewport: { width: 420, height: 1600 } })).newPage();
page.on("pageerror", e => console.log("PAGEERR", e.message));
await page.goto(B+"/auth/signin"); await page.fill("input[type=email]","sam@example.com"); await page.fill("input[type=password]","GuideDemo123!"); await page.click("button[type=submit]"); await page.waitForTimeout(2000);
const order = async () => (await page.locator("button[aria-label$=' up']").evaluateAll(els => els.map(e => e.getAttribute("aria-label").replace(/^Move | up$/g, ""))));
await page.goto(B+"/days/date/2026-10-06"); await page.waitForTimeout(3000);
await page.getByRole("button", { name: /^Reorder$/ }).click(); await page.waitForTimeout(800);
let o = await order(); console.log("before:", o.slice(9, 15).join(", "));
const mover = o[12];
await page.getByRole("button", { name: `Move ${mover} up` }).click(); await page.waitForTimeout(3500);
o = await order(); console.log("after up:", o.slice(9, 15).join(", "));
console.log("offer:", await page.locator("text=Moved for today").innerText().catch(() => "none"));
await page.getByRole("button", { name: "Always" }).click(); await page.waitForTimeout(3000);
o = await order(); console.log("after always:", o.slice(9, 15).join(", "));
await page.screenshot({ path: "/tmp/claude-0/d3.png", clip: { x: 0, y: 0, width: 420, height: 1600 } });
// print sheet order
await page.goto(B+"/days/date/2026-10-06/print"); await page.waitForTimeout(2500);
const txt = await page.locator("body").innerText();
console.log("print has mover after", txt.indexOf(mover) > 0 ? txt.slice(Math.max(0, txt.indexOf(mover) - 150), txt.indexOf(mover) + 20).replace(/\n/g, " / ") : "missing");
await browser.close();
